/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaseProspectsRouteImport } from './routes/base-prospects'
import { Route as CibleRouteImport } from './routes/cible'
import { Route as ProspectsDuJourRouteImport } from './routes/prospects-du-jour'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseProspectsRoute = BaseProspectsRouteImport.update({
  id: '/base-prospects',
  path: '/base-prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const CibleRoute = CibleRouteImport.update({
  id: '/cible',
  path: '/cible',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsDuJourRoute = ProspectsDuJourRouteImport.update({
  id: '/prospects-du-jour',
  path: '/prospects-du-jour',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/base-prospects': typeof BaseProspectsRoute
  '/cible': typeof CibleRoute
  '/prospects-du-jour': typeof ProspectsDuJourRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/base-prospects': typeof BaseProspectsRoute
  '/cible': typeof CibleRoute
  '/prospects-du-jour': typeof ProspectsDuJourRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/base-prospects': typeof BaseProspectsRoute
  '/cible': typeof CibleRoute
  '/prospects-du-jour': typeof ProspectsDuJourRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/base-prospects' | '/cible' | '/prospects-du-jour'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/base-prospects' | '/cible' | '/prospects-du-jour'
  id: '__root__' | '/' | '/base-prospects' | '/cible' | '/prospects-du-jour'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaseProspectsRoute: typeof BaseProspectsRoute
  CibleRoute: typeof CibleRoute
  ProspectsDuJourRoute: typeof ProspectsDuJourRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-prospects': {
      id: '/base-prospects'
      path: '/base-prospects'
      fullPath: '/base-prospects'
      preLoaderRoute: typeof BaseProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cible': {
      id: '/cible'
      path: '/cible'
      fullPath: '/cible'
      preLoaderRoute: typeof CibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects-du-jour': {
      id: '/prospects-du-jour'
      path: '/prospects-du-jour'
      fullPath: '/prospects-du-jour'
      preLoaderRoute: typeof ProspectsDuJourRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaseProspectsRoute: BaseProspectsRoute,
  CibleRoute: CibleRoute,
  ProspectsDuJourRoute: ProspectsDuJourRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
